[project]
name = "encode-solidity"
authors = ["Encode Team"]
description = "A decentralized marketplace protocol for secure job matching"
telemetry = false
requirements = []
[contracts.encode-marketplace]
path = "contracts/encode-marketplace.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
